export const INDONESIA_REGIONS: Record<string, string[]> = {
  "Aceh": ["Banda Aceh", "Sabang", "Lhokseumawe", "Langsa", "Subulussalam", "Aceh Besar", "Aceh Utara"],
  "Sumatera Utara": ["Medan", "Binjai", "Pematangsiantar", "Tanjungbalai", "Tebing Tinggi", "Sibolga", "Padang Sidempuan", "Gunungsitoli", "Deli Serdang", "Simalungun", "Langkat"],
  "Sumatera Barat": ["Padang", "Bukittinggi", "Payakumbuh", "Solok", "Sawahlunto", "Padang Panjang", "Pariaman"],
  "Riau": ["Pekanbaru", "Dumai", "Kampar", "Bengkalis", "Indragiri Hilir"],
  "Kepulauan Riau": ["Tanjungpinang", "Batam", "Bintan", "Karimun"],
  "Jambi": ["Jambi", "Sungai Penuh", "Muaro Jambi"],
  "Bengkulu": ["Bengkulu", "Rejang Lebong"],
  "Sumatera Selatan": ["Palembang", "Lubuklinggau", "Pagar Alam", "Prabumulih", "Ogan Komering Ilir"],
  "Kepulauan Bangka Belitung": ["Pangkalpinang", "Bangka", "Belitung"],
  "Lampung": ["Bandar Lampung", "Metro", "Lampung Selatan"],
  "DKI Jakarta": ["Jakarta Pusat", "Jakarta Utara", "Jakarta Barat", "Jakarta Selatan", "Jakarta Timur", "Kepulauan Seribu"],
  "Jawa Barat": ["Bandung", "Bogor", "Depok", "Bekasi", "Cirebon", "Sukabumi", "Tasikmalaya", "Cimahi", "Banjar", "Garut", "Karawang"],
  "Banten": ["Serang", "Tangerang", "Tangerang Selatan", "Cilegon"],
  "Jawa Tengah": ["Semarang", "Surakarta", "Magelang", "Pekalongan", "Salatiga", "Tegal", "Banyumas", "Cilacap"],
  "DI Yogyakarta": ["Yogyakarta", "Sleman", "Bantul", "Kulon Progo", "Gunungkidul"],
  "Jawa Timur": ["Surabaya", "Malang", "Sidoarjo", "Gresik", "Kediri", "Madiun", "Blitar", "Probolinggo", "Pasuruan", "Mojokerto", "Batu"],
  "Bali": ["Denpasar", "Badung", "Gianyar", "Buleleng", "Tabanan"],
  "Nusa Tenggara Barat": ["Mataram", "Bima", "Lombok Barat"],
  "Nusa Tenggara Timur": ["Kupang", "Ende", "Sikka", "Manggarai"],
  "Kalimantan Barat": ["Pontianak", "Singkawang", "Kubu Raya"],
  "Kalimantan Tengah": ["Palangkaraya", "Kotawaringin Timur"],
  "Kalimantan Selatan": ["Banjarmasin", "Banjarbaru", "Banjar"],
  "Kalimantan Timur": ["Samarinda", "Balikpapan", "Bontang", "Kutai Kartanegara"],
  "Kalimantan Utara": ["Tanjung Selor", "Tarakan"],
  "Sulawesi Utara": ["Manado", "Bitung", "Tomohon", "Kotamobagu"],
  "Gorontalo": ["Gorontalo", "Bone Bolango"],
  "Sulawesi Tengah": ["Palu", "Donggala"],
  "Sulawesi Barat": ["Mamuju", "Majene"],
  "Sulawesi Selatan": ["Makassar", "Gowa", "Maros", "Parepare", "Palopo", "Bone"],
  "Sulawesi Tenggara": ["Kendari", "Baubau"],
  "Maluku": ["Ambon", "Tual"],
  "Maluku Utara": ["Ternate", "Tidore Kepulauan"],
  "Papua": ["Jayapura", "Merauke", "Mimika"],
  "Papua Barat": ["Manokwari", "Sorong"]
};
